/**
 * Design System Component Registry
 *
 * Imports the key visually-distinctive components (Button, Card, Input, Badge)
 * directly from each design system's source files. These have per-system
 * custom Tailwind class treatments (shadows, gradients, borders, etc.).
 *
 * The @/lib/utils import inside these files resolves to the web app's
 * src/lib/utils.ts (same cn() function), so imports work correctly.
 */

// ─── Buttons ───
export { Button as LinearButton, buttonVariants as linearButtonVariants } from "../../../../../../design-systems/linear/components/button"
export { Button as AirbnbButton, buttonVariants as airbnbButtonVariants } from "../../../../../../design-systems/airbnb/components/button"
export { Button as SupabaseButton, buttonVariants as supabaseButtonVariants } from "../../../../../../design-systems/supabase/components/button"
export { Button as CorporateFintechButton, buttonVariants as corporateFintechButtonVariants } from "../../../../../../design-systems/corporate-fintech/components/button"
export { Button as DarkOrangeButton, buttonVariants as darkOrangeButtonVariants } from "../../../../../../design-systems/dark-orange/components/button"
export { Button as VibrantDarkButton, buttonVariants as vibrantDarkButtonVariants } from "../../../../../../design-systems/vibrant-dark/components/button"
export { Button as MinimalLightButton, buttonVariants as minimalLightButtonVariants } from "../../../../../../design-systems/minimal-light/components/button"
export { Button as NeutralMonochromeButton, buttonVariants as neutralMonochromeButtonVariants } from "../../../../../../design-systems/neutral-monochrome/components/button"
export { Button as LightMarketplaceButton, buttonVariants as lightMarketplaceButtonVariants } from "../../../../../../design-systems/light-marketplace/components/button"
export { Button as PrecisionLightButton, buttonVariants as precisionLightButtonVariants } from "../../../../../../design-systems/precision-light/components/button"
export { Button as CinematicDarkButton, buttonVariants as cinematicDarkButtonVariants } from "../../../../../../design-systems/cinematic-dark/components/button"
export { Button as LinearQualityButton, buttonVariants as linearQualityButtonVariants } from "../../../../../../design-systems/linear-quality/components/button"
export { Button as EditorialDarkButton, buttonVariants as editorialDarkButtonVariants } from "../../../../../../design-systems/editorial-dark/components/button"
export { Button as NotionButton, buttonVariants as notionButtonVariants } from "../../../../../../design-systems/notion/components/button"
export { Button as StripeButton, buttonVariants as stripeButtonVariants } from "../../../../../../design-systems/stripe/components/button"
export { Button as VercelButton, buttonVariants as vercelButtonVariants } from "../../../../../../design-systems/vercel/components/button"
export { Button as AppleButton, buttonVariants as appleButtonVariants } from "../../../../../../design-systems/apple/components/button"
export { Button as FigmaButton, buttonVariants as figmaButtonVariants } from "../../../../../../design-systems/figma/components/button"
export { Button as MonoIndustrialButton, buttonVariants as monoIndustrialButtonVariants } from "../../../../../../design-systems/monochrome-industrial/components/button"
export { Button as GlassmorphicDarkButton, buttonVariants as glassmorphicDarkButtonVariants } from "../../../../../../design-systems/glassmorphic-dark/components/button"
export { Button as MidnightGlassButton, buttonVariants as midnightGlassButtonVariants } from "../../../../../../design-systems/midnight-glass/components/button"

// ─── Cards ───
export { Card as LinearCard, CardHeader as LinearCardHeader, CardTitle as LinearCardTitle, CardDescription as LinearCardDescription, CardContent as LinearCardContent, CardFooter as LinearCardFooter } from "../../../../../../design-systems/linear/components/card"
export { Card as AirbnbCard, CardHeader as AirbnbCardHeader, CardTitle as AirbnbCardTitle, CardDescription as AirbnbCardDescription, CardContent as AirbnbCardContent, CardFooter as AirbnbCardFooter } from "../../../../../../design-systems/airbnb/components/card"
export { Card as SupabaseCard, CardHeader as SupabaseCardHeader, CardTitle as SupabaseCardTitle, CardDescription as SupabaseCardDescription, CardContent as SupabaseCardContent, CardFooter as SupabaseCardFooter } from "../../../../../../design-systems/supabase/components/card"
export { Card as CorporateFintechCard, CardHeader as CorporateFintechCardHeader, CardTitle as CorporateFintechCardTitle, CardDescription as CorporateFintechCardDescription, CardContent as CorporateFintechCardContent, CardFooter as CorporateFintechCardFooter } from "../../../../../../design-systems/corporate-fintech/components/card"
export { Card as DarkOrangeCard, CardHeader as DarkOrangeCardHeader, CardTitle as DarkOrangeCardTitle, CardDescription as DarkOrangeCardDescription, CardContent as DarkOrangeCardContent, CardFooter as DarkOrangeCardFooter } from "../../../../../../design-systems/dark-orange/components/card"
export { Card as VibrantDarkCard, CardHeader as VibrantDarkCardHeader, CardTitle as VibrantDarkCardTitle, CardDescription as VibrantDarkCardDescription, CardContent as VibrantDarkCardContent, CardFooter as VibrantDarkCardFooter } from "../../../../../../design-systems/vibrant-dark/components/card"
export { Card as MinimalLightCard, CardHeader as MinimalLightCardHeader, CardTitle as MinimalLightCardTitle, CardDescription as MinimalLightCardDescription, CardContent as MinimalLightCardContent, CardFooter as MinimalLightCardFooter } from "../../../../../../design-systems/minimal-light/components/card"
export { Card as NeutralMonochromeCard, CardHeader as NeutralMonochromeCardHeader, CardTitle as NeutralMonochromeCardTitle, CardDescription as NeutralMonochromeCardDescription, CardContent as NeutralMonochromeCardContent, CardFooter as NeutralMonochromeCardFooter } from "../../../../../../design-systems/neutral-monochrome/components/card"
export { Card as LightMarketplaceCard, CardHeader as LightMarketplaceCardHeader, CardTitle as LightMarketplaceCardTitle, CardDescription as LightMarketplaceCardDescription, CardContent as LightMarketplaceCardContent, CardFooter as LightMarketplaceCardFooter } from "../../../../../../design-systems/light-marketplace/components/card"
export { Card as PrecisionLightCard, CardHeader as PrecisionLightCardHeader, CardTitle as PrecisionLightCardTitle, CardDescription as PrecisionLightCardDescription, CardContent as PrecisionLightCardContent, CardFooter as PrecisionLightCardFooter } from "../../../../../../design-systems/precision-light/components/card"
export { Card as CinematicDarkCard, CardHeader as CinematicDarkCardHeader, CardTitle as CinematicDarkCardTitle, CardDescription as CinematicDarkCardDescription, CardContent as CinematicDarkCardContent, CardFooter as CinematicDarkCardFooter } from "../../../../../../design-systems/cinematic-dark/components/card"
export { Card as LinearQualityCard, CardPoster as LinearQualityCardPoster, CardMedia as LinearQualityCardMedia, CardLabel as LinearQualityCardLabel, CardHeader as LinearQualityCardHeader, CardTitle as LinearQualityCardTitle, CardDescription as LinearQualityCardDescription, CardContent as LinearQualityCardContent, CardFooter as LinearQualityCardFooter } from "../../../../../../design-systems/linear-quality/components/card"
export { Card as EditorialDarkCard, CardMedia as EditorialDarkCardMedia, CardHeader as EditorialDarkCardHeader, CardTitle as EditorialDarkCardTitle, CardDescription as EditorialDarkCardDescription, CardContent as EditorialDarkCardContent, CardFooter as EditorialDarkCardFooter } from "../../../../../../design-systems/editorial-dark/components/card"
export { Card as NotionCard, CardHeader as NotionCardHeader, CardTitle as NotionCardTitle, CardDescription as NotionCardDescription, CardContent as NotionCardContent, CardFooter as NotionCardFooter } from "../../../../../../design-systems/notion/components/card"
export { Card as StripeCard, CardHeader as StripeCardHeader, CardTitle as StripeCardTitle, CardDescription as StripeCardDescription, CardContent as StripeCardContent, CardFooter as StripeCardFooter } from "../../../../../../design-systems/stripe/components/card"
export { Card as VercelCard, CardHeader as VercelCardHeader, CardTitle as VercelCardTitle, CardDescription as VercelCardDescription, CardContent as VercelCardContent, CardFooter as VercelCardFooter } from "../../../../../../design-systems/vercel/components/card"
export { Card as AppleCard, CardHeader as AppleCardHeader, CardTitle as AppleCardTitle, CardDescription as AppleCardDescription, CardContent as AppleCardContent, CardFooter as AppleCardFooter } from "../../../../../../design-systems/apple/components/card"
export { Card as FigmaCard, CardHeader as FigmaCardHeader, CardTitle as FigmaCardTitle, CardDescription as FigmaCardDescription, CardContent as FigmaCardContent, CardFooter as FigmaCardFooter } from "../../../../../../design-systems/figma/components/card"
export { Card as MonoIndustrialCard, CardHeader as MonoIndustrialCardHeader, CardTitle as MonoIndustrialCardTitle, CardDescription as MonoIndustrialCardDescription, CardContent as MonoIndustrialCardContent, CardFooter as MonoIndustrialCardFooter } from "../../../../../../design-systems/monochrome-industrial/components/card"
export { Card as GlassmorphicDarkCard, CardHeader as GlassmorphicDarkCardHeader, CardTitle as GlassmorphicDarkCardTitle, CardDescription as GlassmorphicDarkCardDescription, CardContent as GlassmorphicDarkCardContent, CardFooter as GlassmorphicDarkCardFooter } from "../../../../../../design-systems/glassmorphic-dark/components/card"
export { Card as MidnightGlassCard, CardHeader as MidnightGlassCardHeader, CardTitle as MidnightGlassCardTitle, CardDescription as MidnightGlassCardDescription, CardContent as MidnightGlassCardContent, CardFooter as MidnightGlassCardFooter } from "../../../../../../design-systems/midnight-glass/components/card"

// ─── Inputs ───
export { Input as LinearInput } from "../../../../../../design-systems/linear/components/input"
export { Input as AirbnbInput } from "../../../../../../design-systems/airbnb/components/input"
export { Input as SupabaseInput } from "../../../../../../design-systems/supabase/components/input"
export { Input as CorporateFintechInput } from "../../../../../../design-systems/corporate-fintech/components/input"
export { Input as DarkOrangeInput } from "../../../../../../design-systems/dark-orange/components/input"
export { Input as VibrantDarkInput } from "../../../../../../design-systems/vibrant-dark/components/input"
export { Input as MinimalLightInput } from "../../../../../../design-systems/minimal-light/components/input"
export { Input as NeutralMonochromeInput } from "../../../../../../design-systems/neutral-monochrome/components/input"
export { Input as LightMarketplaceInput } from "../../../../../../design-systems/light-marketplace/components/input"
export { Input as PrecisionLightInput } from "../../../../../../design-systems/precision-light/components/input"
export { Input as CinematicDarkInput } from "../../../../../../design-systems/cinematic-dark/components/input"
export { Input as LinearQualityInput } from "../../../../../../design-systems/linear-quality/components/input"
export { Input as EditorialDarkInput } from "../../../../../../design-systems/editorial-dark/components/input"
export { Input as NotionInput } from "../../../../../../design-systems/notion/components/input"
export { Input as StripeInput } from "../../../../../../design-systems/stripe/components/input"
export { Input as VercelInput } from "../../../../../../design-systems/vercel/components/input"
export { Input as AppleInput } from "../../../../../../design-systems/apple/components/input"
export { Input as FigmaInput } from "../../../../../../design-systems/figma/components/input"
export { Input as MonoIndustrialInput } from "../../../../../../design-systems/monochrome-industrial/components/input"
export { Input as GlassmorphicDarkInput } from "../../../../../../design-systems/glassmorphic-dark/components/input"
export { Input as MidnightGlassInput } from "../../../../../../design-systems/midnight-glass/components/input"

// ─── Badges ───
export { Badge as LinearBadge } from "../../../../../../design-systems/linear/components/badge"
export { Badge as AirbnbBadge } from "../../../../../../design-systems/airbnb/components/badge"
export { Badge as SupabaseBadge } from "../../../../../../design-systems/supabase/components/badge"
export { Badge as CorporateFintechBadge } from "../../../../../../design-systems/corporate-fintech/components/badge"
export { Badge as DarkOrangeBadge } from "../../../../../../design-systems/dark-orange/components/badge"
export { Badge as VibrantDarkBadge } from "../../../../../../design-systems/vibrant-dark/components/badge"
export { Badge as MinimalLightBadge } from "../../../../../../design-systems/minimal-light/components/badge"
export { Badge as NeutralMonochromeBadge } from "../../../../../../design-systems/neutral-monochrome/components/badge"
export { Badge as LightMarketplaceBadge } from "../../../../../../design-systems/light-marketplace/components/badge"
export { Badge as PrecisionLightBadge } from "../../../../../../design-systems/precision-light/components/badge"
export { Badge as CinematicDarkBadge } from "../../../../../../design-systems/cinematic-dark/components/badge"
export { Badge as LinearQualityBadge } from "../../../../../../design-systems/linear-quality/components/badge"
export { Badge as EditorialDarkBadge } from "../../../../../../design-systems/editorial-dark/components/badge"
export { Badge as NotionBadge } from "../../../../../../design-systems/notion/components/badge"
export { Badge as StripeBadge } from "../../../../../../design-systems/stripe/components/badge"
export { Badge as VercelBadge } from "../../../../../../design-systems/vercel/components/badge"
export { Badge as AppleBadge } from "../../../../../../design-systems/apple/components/badge"
export { Badge as FigmaBadge } from "../../../../../../design-systems/figma/components/badge"
export { Badge as MonoIndustrialBadge } from "../../../../../../design-systems/monochrome-industrial/components/badge"
export { Badge as GlassmorphicDarkBadge } from "../../../../../../design-systems/glassmorphic-dark/components/badge"
export { Badge as MidnightGlassBadge } from "../../../../../../design-systems/midnight-glass/components/badge"

// ─── Code Tabs ───
export { CodeTabs as LinearCodeTabs } from "../../../../../../design-systems/linear/components/code-tabs"
export { CodeTabs as AirbnbCodeTabs } from "../../../../../../design-systems/airbnb/components/code-tabs"
export { CodeTabs as SupabaseCodeTabs } from "../../../../../../design-systems/supabase/components/code-tabs"
export { CodeTabs as CorporateFintechCodeTabs } from "../../../../../../design-systems/corporate-fintech/components/code-tabs"
export { CodeTabs as DarkOrangeCodeTabs } from "../../../../../../design-systems/dark-orange/components/code-tabs"
export { CodeTabs as VibrantDarkCodeTabs } from "../../../../../../design-systems/vibrant-dark/components/code-tabs"
export { CodeTabs as MinimalLightCodeTabs } from "../../../../../../design-systems/minimal-light/components/code-tabs"
export { CodeTabs as NeutralMonochromeCodeTabs } from "../../../../../../design-systems/neutral-monochrome/components/code-tabs"
export { CodeTabs as LightMarketplaceCodeTabs } from "../../../../../../design-systems/light-marketplace/components/code-tabs"
export { CodeTabs as PrecisionLightCodeTabs } from "../../../../../../design-systems/precision-light/components/code-tabs"
export { CodeTabs as CinematicDarkCodeTabs } from "../../../../../../design-systems/cinematic-dark/components/code-tabs"
export { CodeTabs as LinearQualityCodeTabs } from "../../../../../../design-systems/linear-quality/components/code-tabs"
export { CodeTabs as EditorialDarkCodeTabs } from "../../../../../../design-systems/editorial-dark/components/code-tabs"
export { CodeTabs as NotionCodeTabs } from "../../../../../../design-systems/notion/components/code-tabs"
export { CodeTabs as StripeCodeTabs } from "../../../../../../design-systems/stripe/components/code-tabs"
export { CodeTabs as VercelCodeTabs } from "../../../../../../design-systems/vercel/components/code-tabs"
export { CodeTabs as AppleCodeTabs } from "../../../../../../design-systems/apple/components/code-tabs"
export { CodeTabs as FigmaCodeTabs } from "../../../../../../design-systems/figma/components/code-tabs"
export { CodeTabs as MonoIndustrialCodeTabs } from "../../../../../../design-systems/monochrome-industrial/components/code-tabs"
export { CodeTabs as GlassmorphicDarkCodeTabs } from "../../../../../../design-systems/glassmorphic-dark/components/code-tabs"
export { CodeTabs as MidnightGlassCodeTabs } from "../../../../../../design-systems/midnight-glass/components/code-tabs"

// ─── Cursors ───
export { Cursor as LinearCursor } from "../../../../../../design-systems/linear/components/cursor"
export { Cursor as AirbnbCursor } from "../../../../../../design-systems/airbnb/components/cursor"
export { Cursor as SupabaseCursor } from "../../../../../../design-systems/supabase/components/cursor"
export { Cursor as CorporateFintechCursor } from "../../../../../../design-systems/corporate-fintech/components/cursor"
export { Cursor as DarkOrangeCursor } from "../../../../../../design-systems/dark-orange/components/cursor"
export { Cursor as VibrantDarkCursor } from "../../../../../../design-systems/vibrant-dark/components/cursor"
export { Cursor as MinimalLightCursor } from "../../../../../../design-systems/minimal-light/components/cursor"
export { Cursor as NeutralMonochromeCursor } from "../../../../../../design-systems/neutral-monochrome/components/cursor"
export { Cursor as LightMarketplaceCursor } from "../../../../../../design-systems/light-marketplace/components/cursor"
export { Cursor as PrecisionLightCursor } from "../../../../../../design-systems/precision-light/components/cursor"
export { Cursor as CinematicDarkCursor } from "../../../../../../design-systems/cinematic-dark/components/cursor"
export { Cursor as LinearQualityCursor } from "../../../../../../design-systems/linear-quality/components/cursor"
export { Cursor as EditorialDarkCursor } from "../../../../../../design-systems/editorial-dark/components/cursor"
export { Cursor as NotionCursor } from "../../../../../../design-systems/notion/components/cursor"
export { Cursor as StripeCursor } from "../../../../../../design-systems/stripe/components/cursor"
export { Cursor as VercelCursor } from "../../../../../../design-systems/vercel/components/cursor"
export { Cursor as AppleCursor } from "../../../../../../design-systems/apple/components/cursor"
export { Cursor as FigmaCursor } from "../../../../../../design-systems/figma/components/cursor"
export { Cursor as MonoIndustrialCursor } from "../../../../../../design-systems/monochrome-industrial/components/cursor"
export { Cursor as GlassmorphicDarkCursor } from "../../../../../../design-systems/glassmorphic-dark/components/cursor"
export { Cursor as MidnightGlassCursor } from "../../../../../../design-systems/midnight-glass/components/cursor"
export { Spinner as MonoIndustrialSpinner } from "../../../../../../design-systems/monochrome-industrial/components/spinner"
